version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - 7782:80
    volumes:
      - ./nginx-app/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-app/logs/:/var/log/postgresql
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    depends_on:
      - core

  core:
    build:
      context: ./backend-app
    env_file:
      - ./core.env
      - ./db.env
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - ./db.env
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
  static:
  media:
